### ISSUE TITLE
Final project quick presentation - guiding questions

### ISSUE THREAD

**Issue by masongallo** [cbachu92/datascience_cb#2]
Are you concerned about matching names? What if 2 people have the same name? What about player injuries? Can you cite an overall percentage of players that get injured?

**Comment by cbachu92** [comment]
Thanks Mason. The name-matching was one of my biggest concerns initially however, I'm not so concerned with it after exploring the data a bit; this database stores people's names in a unique way. I'm not totally sure how they decide on it, but they use multiple initials and then a last name. This ensures uniqueness. The only drawback of this is that I can only match the full names of players (not first or last), but that wouldn't have much implication, if any. Secondly, injury rates may be high however there's no way to tell if the injury is responsible for an U-19 player not being promoted to the highest level of the game. If there is a statistic on specifically career-ending injuries for U-19 players, that would be awesome to include just for perspective. I'll look for that information. I really appreciate the feedback.
